module.exports = {
    UPDATE_BEERS: "UPDATE_BEERS",
    PUSH_BEERS: "PUSH_BEERS",
    DELETE_BEERS: "DELETE_BEERS",
    PLACE_ORDER: "PLACE_ORDER",
    GET_ORDERS: "GET_ORDERS",
    EXEC_ORDER: "EXEC_ORDER"
}